### ISSUE TITLE
Style : 전반적인 CSS 수정

### ISSUE THREAD

**Issue by marugy** [Lets-Travel-Well/are-you-alone-frontend#26]
### 🗄️ 종류

issue 종류를 선택하세요
- [ ] Style

## 🔍Description

> 사용자 입장에서 서비스 부분에 대한 CSS 수정

## 📝Todo

- [ ] 로그인 수정
- [ ] 메인 페이지 수정 ( 핫플레이스 )
- [ ] 지도 사이즈 수정
- [ ] 검색 결과 수정
- [ ] 동행 리스트 수정
- [ ] 동행 상세보기 수정
