### ISSUE TITLE
feat : 메인페이지 변경, 마이페이지

### ISSUE THREAD

**Issue by non-inss** [Lets-Travel-Well/are-you-alone-frontend#32]
## 🔍Description

- MainHomeView view추가하고, 전역가드로 로그인해야 페이지 이동되게 수정하였습니다. 수정한 view는 현재 틀만 잡았습니다.
- userpage 폴더속 MypageView 팔로우, 팔로잉, 관심있는여행목록, 관심있는 여행 계획목록 

## 📝Todo

- [ ] 신청 수락 및 거절
- [ ] private한 여행 계획
- [ ] 개인정보 수정 기능
