### ISSUE TITLE
feat: 마이페이지(관심있는여행, 내가 리더인 여행, 내가 신청한여행, 발자취점수)

### ISSUE THREAD

**Issue by non-inss** [Lets-Travel-Well/are-you-alone-frontend#52]
## 🔍Description

 마이페이지(관심있는여행, 내가 리더인 여행, 내가 신청한여행, 발자취점수)

## 📝Todo

- [ ] 관심있는 여행지
- [ ] 내가 리더인 여행
- [ ] 수락대기 상태 여행 
- [ ] 진행중 상태 여행
- [ ] 거절된 상태 여행
- [ ] 완료 상태 여행
- [ ] 발자취 점수
