### ISSUE TITLE
feat : 마이페이지 팔로우 버튼 값 변경, 마이페이지유저 - 로그인유저 변수 설정

### ISSUE THREAD

**Issue by yhj0214** [Lets-Travel-Well/are-you-alone-frontend#83]
## 🔍Description

> 마이페이지 state 정리

## 📝Todo

- [ ] 로그인 사용자와 마이페이지 유저가 같을 경우 버튼 삭제
- [ ] 마이페이지 유저 - 로그인 유저 변수 설정
- [ ] 마이페이지 유저 저장
