### ISSUE TITLE
feat : 동행 신청 상태에 따라 다른 액션의 버튼 구현

### ISSUE THREAD

**Issue by marugy** [Lets-Travel-Well/are-you-alone-frontend#84]
## 🔍Description

> 동행 신청 상태에 따라 다른 액션의 버튼 구현

## 📝Todo

- [ ] 동행 상세보기에서 신청 상태 받아오기
- [ ] 내가 작성한 동행이 아닌 것에만 버튼 출력
- [ ] 미신청 신청 승인 거부 상태로 분류
- [ ] 해당 상태에 따라 이미지 모양과 aciton이 달라지도록 구현
